src/index.js
src/style/style.css

- Fix navigation with new bootstrap

- Update version of bootstrap used

---

src/components/ui/appheadernavigation/appheadernavigation.main.jsx
src/components/ui/categoryitems/categoryitems.main.jsx
src/components/ui/productlist/productlist.main.jsx
src/components/ui/productlistpaginationbottom/productlistpaginationbottom.main.jsx
src/components/ui/productlistpaginationtop/productlistpaginationtop.main.jsx
src/components/ui/searchresultsitems/searchresultsitems.main.jsx
src/style/style.css

- Implementation for displaying sub-categories

---

src/components/pages/CartPage/CartPage.jsx
src/components/pages/ProfilePage/ProfilePage.jsx
src/components/ui/categoryitems/categoryitems.main.jsx
src/components/ui/productdisplayitem/productdisplayitem.main.jsx
src/components/ui/productlist/productlist.main.jsx
src/components/ui/productlistitem/productlistitem.main.jsx
src/components/ui/productlistpaginationbottom/productlistpaginationbottom.main.jsx
src/components/ui/productlistpaginationtop/productlistpaginationtop.main.jsx
src/components/ui/productlistsearchresults/productlistsearchresults.main.jsx
src/components/ui/searchresultsitems/searchresultsitems.main.jsx
src/style/style.css

- Add loading indicators for pages

- Fix routing defects

---

src/components/pages/CartPage/CartPage.jsx
src/components/pages/CheckoutAuthPage/CheckoutAuthPage.jsx
src/components/pages/CheckoutPage/CheckoutPage.jsx
src/components/pages/EditAddressPage/EditAddressPage.jsx
src/components/pages/NewAddressPage/NewAddressPage.jsx
src/components/pages/NewPaymentPage/NewPaymentPage.jsx
src/components/ui/addressform/addressform.main.jsx
src/components/ui/cart/cart.lineitem.jsx
src/components/ui/cart/cart.main.jsx
src/components/ui/checkout/checkout.summarylist.jsx
src/components/ui/paymentform/paymentform.main.jsx
src/components/ui/registrationform/registrationform.main.jsx
src/style/style.css

Hi Shaun, please review the changes for checkout page.
This will complete the following stories:
- Add New Shipping Address
- Select from Existing Shipping Address
- Select Shipping Service Level

Checkout page

---

src/components/ui/appheadernavigation/appheadernavigation.main.jsx
src/components/ui/categoryitems/categoryitems.main.jsx
src/components/ui/productdisplayitem/productdisplayitem.main.jsx
src/components/ui/productlist/productlist.main.jsx
src/components/ui/productlistitem/productlistitem.main.jsx
src/components/ui/productlistpaginationbottom/productlistpaginationbottom.main.jsx
src/components/ui/productlistpaginationtop/productlistpaginationtop.main.jsx
src/components/ui/productlistsearchresults/productlistsearchresults.main.jsx

- Update fetches to not hardcode urls

- Update urls for simple forms

---

package.json
webpack.config.js

- Update dependencies to include workbox
- Implement new service worker

- Update dependencies to remove sw-precache

---

src/App.js
src/components/appheaderlogin.main.jsx
src/components/appheadersearch.main.jsx
src/components/categoryitems.main.jsx
src/components/productdisplayitem.main.jsx
src/components/productlist.main.jsx
src/components/productlistitem.main.jsx
src/components/productlistpaginationbottom.main.jsx
src/components/productlistpaginationtop.main.jsx
src/components/registrationform.main.jsx
src/components/searchresultsitems.main.jsx
src/containers/CategoryPage.jsx
src/containers/ProductDetailPage.jsx
src/containers/ProfilePage.jsx
src/containers/SearchResultsPage.jsx
src/utils/AuthService.js

- Ensure calls are not made directly to coretex, but through rel where needed

- Mass linting cleanup

---

.eslintrc
package-lock.json
src/components/addressform.main.jsx
src/components/checkout.summarylist.jsx
src/containers/CheckoutAuthPage.jsx
src/containers/CheckoutPage.jsx
src/containers/OrderReviewPage.jsx
src/routes.js

now able to add payments to order, and if everything is selected, proceed to order review page.

Proceed to Order Review Page

---

src/components/cart.lineitem.jsx
src/components/cart.main.jsx
src/components/checkout.summarylist.jsx
src/containers/CartPage.jsx
src/containers/CheckoutAuthPage.jsx

Fixing lint errors in cart/checkout pages. after this 47 problems remain with linting, all in src/components/productrecommendations.main.jsx

Fixed linting errors

---

CONTRIBUTING.md
src/components/orderhistory.main.jsx
src/components/orderhistoryline.main.jsx
src/components/orderline.main.jsx
src/components/profileInfo.main.jsx
src/containers/OrderHistoryPage.jsx
src/containers/ProfilePage.jsx
src/routes.js

- Display some order information

- Profile page display

---

src/components/profileInfo.main.jsx
src/components/profileaddresses.main.jsx
src/components/profilepaymentmethods.main.jsx
src/containers/ProfilePage.jsx

- Need to add link to view individual order info

- Profile page displays payment methods, name, addresses, orders

---

src/components/address.container.jsx
src/components/cart.lineitem.jsx
src/components/ordertable.lineitem.jsx
src/components/ordertable.main.jsx
src/components/paymentmethod.container.jsx
src/components/shippingoption.container.jsx
src/containers/CartPage.jsx
src/containers/CheckoutPage.jsx
src/containers/OrderReviewPage.jsx
src/style/style.css

finally able to complete full checkout flow.

Added Order Review Page, can complete checkout now

---

src/components/appheadernavigation.main.jsx

- Indicates login service failed

- Display maintenance page when login fails too

---

src/components/appheadernavigation.main.jsx

Joined two nested promises into one promise. Also removed duplicated `catch` code.

Flattened nested promises into one promise

---

src/components/appheadernavigation.main.jsx

Fixed lint error introduced with previous commit.

Fixed linting error

---

package-lock.json
package.json
src/components/orderline.main.jsx
webpack/webpack.config.base.js

- Update cache config for workbox
- Fix displaying order status in Profile Page

- Update Workbox version used

---

.editorconfig
package-lock.json
src/components/purchasedetails.main.jsx
src/containers/CheckoutPage.jsx
src/containers/OrderReviewPage.jsx

fixed bug where checkout expected shipment to be present in all orders, which is not the case.

Fixed Bug reported in checkout flow

---

src/components/orderhistory.main.jsx

- Add render for cases where no previous orders exist

- Add check for number of purchases

---

src/components/appheader.main.jsx
src/components/appheaderlocale.main.jsx
src/components/appheaderlogin.main.jsx
src/components/productdisplayitem.main.jsx
src/style/style.css

- Move elements around on navigation bar
- Fix navigation bar width on mobile

- Clean up navigation a bit

---

src/style/style.css

looks like when I was creating styles for order-container, I left two order-container instead of one cart + one order

Fixed style bug in cart mobile

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md

- Update README

---

src/components/appheader.main.jsx
src/components/appheadernavigation.main.jsx
src/containers/ProfilePage.jsx
src/localization/en-CA.json
src/localization/fr-FR.json
src/style/style.css
webpack/webpack.config.prod.js

- Add proper network offline alert
- Fix profile page layout when loading
- Disable proxy for production

Network Offline check

---

src/ep.config.json

Revert Tracking ID

---

src/containers/OrderReviewPage.jsx

Fix showing deliveries in Analytics

---

src/components/cart.lineitem.jsx

Log analytics first

---

src/components/productlistitem.main.jsx
src/style/style.css

- Fix linting errors
- Fix styles on category page

Fix Linting and styles

---

README.md

- Need to set liquibase contexts correctly to ensure only loading ep-blueprint data

Update step for resetting database data

---

.dockerignore
.gitignore
README.md
docker/prod/Dockerfile
docker/prod/docker-compose.yaml
docker/prod/nginx.conf
package-lock.json
package.json

This PR adds a new `Dockerfile` that builds a "production ready" docker image based on `nginx` server. It is accompanied with Jsnkis task http://builds.elasticpath.net/pd/job/Reference-store/job/rs-deploy-prod/ that builds and deploys an image to an http://52.89.63.103/.

Production deployment

---

webpack/webpack.config.dev.js

This PR enables source maps in development mode.

Enabled sourcemaps in dev mode

---

test/src/main/java/com/elasticpath/selenium/pages/HeaderPage.java
test/src/test/resources/com.elasticpath.cucumber/purchase/Purchase.feature

- Fix AUT after mobile changes

Fix AUT runs

---

src/components/addressform.main.jsx

- Invoke geo api directly for 7.3

Update country selection to work with 7.3
